/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ro.rs.findjar4class.gui;

import java.nio.file.Paths;
import java.util.List;
import java.util.Map;
import java.util.function.Predicate;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import ro.rs.findjar4class.logic.ClassFinder;
import ro.rs.findjar4class.logic.FileIndexer;
import ro.rs.findjar4class.util.Utils;

/**
 *
 * @author rsinorchian
 */
public class Find extends javax.swing.JFrame {

    private final FileIndexer fileIndexer = FileIndexer.getInstance();
    private final ClassFinder classFinder;
    private List<String> results;
    private String previousSearch;
    private int sameSearchCounter = 0;
    private DefaultListModel listModel;

    /**
     * Creates new form Find
     */
    public Find() {
        initComponents();
        this.listModel = new DefaultListModel();
        this.resultList.setModel(this.listModel);
        classFinder = new ClassFinder(listModel);
        fileIndexer.loadExistingIndex();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jarFolderTextField = new javax.swing.JTextField();
        classNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        indexJars = new javax.swing.JButton();
        searchClass = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jarFolderTextField.setText("Enter the path of the folder which contains the jars");
        jarFolderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jarFolderTextFieldActionPerformed(evt);
            }
        });

        classNameTextField.setText("Enter class name. Wildcards can be used with *");

        jLabel1.setText("Step 2: Search the class in the folder with jars");

        jLabel2.setText("Jars folder");

        jLabel3.setText("Class name");

        indexJars.setText("Index jars");
        indexJars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexJarsActionPerformed(evt);
            }
        });

        searchClass.setText("Search class");
        searchClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchClassActionPerformed(evt);
            }
        });

        jLabel4.setText("Step 1: Index the jar folder");

        resultList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(resultList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(classNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jarFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchClass, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(indexJars, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4))
                        .addGap(0, 128, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jarFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(indexJars)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(searchClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jarFolderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jarFolderTextFieldActionPerformed
    }//GEN-LAST:event_jarFolderTextFieldActionPerformed

    private void indexJarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexJarsActionPerformed
        FileIndexer.IndexerThread indexerThread = this.fileIndexer.new IndexerThread(jarFolderTextField);
        indexerThread.start();
    }//GEN-LAST:event_indexJarsActionPerformed

    private void searchClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchClassActionPerformed
        String findWhat = this.classNameTextField.getText();
        classFinder.findClass(findWhat);
    }//GEN-LAST:event_searchClassActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField classNameTextField;
    private javax.swing.JButton indexJars;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jarFolderTextField;
    private javax.swing.JList resultList;
    private javax.swing.JButton searchClass;
    // End of variables declaration//GEN-END:variables
}
